---
# tasks file for db
- name: Change mongo config file
  become: yes
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  tags: db-tag
  notify: restart mongo

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
